name: Redeploy GitHub Pages

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Commit empty change
        run: |
          git config --global user.email "Azhargamer15@gmail.com"
          git config --global user.name "Azhar"
          git commit --allow-empty -m "Trigger Pages rebuild"
          git push
